package com.cadre.server.core.event;

public enum EventTopics {
	NEW_USER,
	PO_LOGIN_RESPONSE,
	PO_LOGIN_REQUEST,
	EVENT_BEFORE_READ_ENTITY_SET_DATA,
	EVENT_AFTER_READ_ENTITY_SET_DATA,
	EVENT_AFTER_READ_ENTITY_DATA,
	EVENT_BEFORE_READ_ENTITY_DATA;
}
